data_group_by: ["Email"]

placeholders:
  approver_table:
    type: "table"
    group_by: ["Email"]
#    agg:
#      EmployeeName: "count"
    columns: ["reqnum", "User", "approver"]

  manager_summary:
    type: "list"
    group_by: ["ManagerName"]
    agg:
      EmployeeName: "count"
    text_format: "{ManagerName} manages {EmployeeName} employees"
    format: "ul"